
services:
  clientst:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      no_cache: true
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/student
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  postgres:
    container_name: serviceDb
    image: postgres:17.4
    environment:
      POSTGRES_DB: student
      POSTGRES_USER: user
      POSTGRES_PASSWORD : pass
    ports:
      - "15432:5432"
    volumes:
      - ./initialization/:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  client-network:
    driver: bridge

volumes:
  data: